title: DITA Open Toolkit
description: DITA Open Toolkit is an implementation of the OASIS DITA XML Specification.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
